### ISSUE TITLE
App crashes many times

### ISSUE THREAD

**Issue by ducnguyenhuy** [DoAnhKien/FlutterBaseGetX#1]

**Comment by DoAnhKien** [comment]
can you give me more evidence

**Comment by DoAnhKien** [comment]
can you guys prove that

**Comment by ducnguyenhuy** [comment]
i guess so =)))

**Comment by Chung14011998** [comment]
Vler, why do you close this issue when the app is still crashed?

**Comment by ducnguyenhuy** [comment]
because mr Kien can not fix it =)))

**Comment by ducnguyenhuy** [comment]
why don't you reply to us? Are you being scolded by your boss?

**Comment by DoAnhKien** [comment]
yes, can you help me for this issue ?

**Comment by ducnguyenhuy** [comment]
no, i can not hehe
